package net.ddns.anderserver.keephome.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006497)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFcae6ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001e31)
val md_theme_light_secondary = Color(0xFF2140ff)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdde0ff)
val md_theme_light_onSecondaryContainer = Color(0xFF000866)
val md_theme_light_tertiary = Color(0xFF00658e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc3e7ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001e2e)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFdee3ea)
val md_theme_light_onSurfaceVariant = Color(0xFF41474d)
val md_theme_light_outline = Color(0xFF72787e)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2d3132)

val md_theme_dark_primary = Color(0xFF8ccdff)
val md_theme_dark_onPrimary = Color(0xFF003350)
val md_theme_dark_primaryContainer = Color(0xFF004b73)
val md_theme_dark_onPrimaryContainer = Color(0xFFcae6ff)
val md_theme_dark_secondary = Color(0xFFbbc3ff)
val md_theme_dark_onSecondary = Color(0xFF0013a0)
val md_theme_dark_secondaryContainer = Color(0xFF0020de)
val md_theme_dark_onSecondaryContainer = Color(0xFFdde0ff)
val md_theme_dark_tertiary = Color(0xFF7fcfff)
val md_theme_dark_onTertiary = Color(0xFF00344b)
val md_theme_dark_tertiaryContainer = Color(0xFF004c6c)
val md_theme_dark_onTertiaryContainer = Color(0xFFc3e7ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF41474d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c7ce)
val md_theme_dark_outline = Color(0xFF8b9198)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)

val seed = Color(0xFF00aeff)
val error = Color(0xFFba1b1b)